name: Auto Deploy Node.js App

on:
  push:
    branches:
      - main  # your deployment branch

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server and Run Prisma Migrations
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "🔁 Switching to project directory"
            cd /home/backend

            echo "🔐 Git safe directory setup"
            git config --global --add safe.directory /home/backend

            echo "📥 Pulling latest code"
            git pull origin main

            echo "📦 Installing dependencies"
            npm install

            echo "🛠️ Running Prisma migrations with .env"
            npx -y dotenv -e .env -- npx prisma migrate deploy

            echo "🚀 Restarting backend server"
            pm2 restart web-monitor-server
